name: HungerNoMore
version: '${project.version}'
main: com.duskanalog.www.HungerNoMore
api-version: '1.20'
authors: [Vykyan]
website: https://www.duskanalog.com
description: A plugin that modifies hunger and healing mechanics

commands:
  hungernomore:
    description: Main command for HungerNoMore plugin
    usage: /<command> reload
    aliases: [hnm]
    permission: hungernomore.admin

permissions:
  hungernomore.admin:
    description: Allows access to admin commands
    default: op
  hungernomore.bypass:
    description: Allows bypassing plugin effects
    default: op